name: 'Build preCICE'
description: 'Installs preCICE in $HOME/precice and adds it to the path.'

inputs:
  precice-version:
    required: true
    default: 'develop'
    description: 'The version of preCICE to use. Can be a branch or tag or SHA. Defaults to `develop`'
  build-tests:
    required: false
    default: 'OFF'
    description: 'Whether to build tests. Default is `OFF`'

runs:
  using: "composite"
  steps: 
    - name: check out repository # clone to $HOME/precice
      uses: actions/checkout@v3
      with:
        repository: precice/precice
        ref: ${{ inputs.precice-version }}
        path: precice
      env: 
        GITHUB_WORKSPACE: $HOME
    
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake libeigen3-dev libxml2-dev libboost-all-dev petsc-dev python3-dev python3-numpy
      shell: bash

    - name: Generate build directory
      shell: bash
      working-directory: precice
      env: 
        GITHUB_WORKSPACE: $HOME
      run: mkdir -p build

    - name: Configure
      shell: bash
      working-directory: precice/build
      env:
        GITHUB_WORKSPACE: $HOME
      run: |
        cmake --version
        cmake -DCMAKE_INSTALL_PREFIX=$HOME/precice -DCMAKE_BUILD_TYPE=Release -DPRECICE_PETScMapping=OFF -DPRECICE_Python_Actions=OFF -DBUILD_TESTING=${{ inputs.build-tests }} ..

    - name: Compile
      shell: bash
      working-directory: precice/build
      env:
        GITHUB_WORKSPACE: $HOME
      run: |
        make -j $(nproc)

    - name: Install
      shell: bash
      working-directory: precice/build
      env:
        GITHUB_WORKSPACE: $HOME
      run: make install

    - name: Add to path
      shell: bash
      run: |
        echo "PATH=$HOME/precice/bin:$PATH" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$HOME/precice/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=$HOME/precice/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
        echo "CPATH=$HOME/precice/include:$CPATH" >> $GITHUB_ENV
        echo "CMAKE_PREFIX_PATH=$HOME/precice:$CMAKE_PREFIX_PATH" >> $GITHUB_ENV