name: 'Build preCICE'
description: 'Installs preCICE in  and adds it to the path.'

inputs:
  precice-version:
    required: true
    default: 'develop'
    description: 'The version of preCICE to use. Can be a branch or tag or SHA. Defaults to `develop`'
  build-tests:
    required: false
    default: 'OFF'
    description: 'Whether to build tests. Defaults to `OFF`'

runs:
  using: "composite"
  steps: 
    - name: check out repository
      uses: actions/checkout@v3
      with:
        repository: precice/precice
        ref: ${{ inputs.precice-version }}
        path: precice
    
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake libeigen3-dev libxml2-dev libboost-all-dev petsc-dev python3-dev python3-numpy
      shell: bash

    - name: Generate build directory
      working-directory: $GITHUB_WORKSPACE/precice/build
      run: mkdir -p build
      shell: bash

    - name: Configure
      working-directory: $GITHUB_WORKSPACE/precice/build
      run: |
        cmake --version
        cmake -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/precice -DCMAKE_BUILD_TYPE=Release -DPRECICE_PETScMapping=OFF -DPRECICE_Python_Actions=OFF -DBUILD_TESTING=${{ inputs.build-tests }} ..
      shell: bash

    - name: Compile
      working-directory: $GITHUB_WORKSPACE/precice/build
      run: |
        make -j $(nproc)
      shell: bash

    - name: Install
      working-directory: $GITHUB_WORKSPACE/precice/build
      run: make install
      shell: bash

    - name: Add to path
      run: |
        export PATH=$GITHUB_WORKSPACE/precice/bin:$PATH
        export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/precice/lib:$LD_LIBRARY_PATH
        export PKG_CONFIG_PATH=$GITHUB_WORKSPACE/precice/lib/pkgconfig:$PKG_CONFIG_PATH
        export CPATH=$PRECICE_PREFIX/include:$CPATH
        export CMAKE_PREFIX_PATH=$PRECICE_PREFIX:$CMAKE_PREFIX_PATH
      shell: bash