name: 'Build preCICE'
description: 'Installs preCICE in $GITHUB_WORKSPACE/precice and adds it to the path.'

inputs:
  precice-version:
    required: true
    default: 'develop'
    description: 'The version of preCICE to use. Can be a branch or tag or SHA. Defaults to `develop`'
  build-tests:
    required: false
    default: 'OFF'
    description: 'Whether to build tests. Defaults to `OFF`'

runs:
  using: "composite"
  defaults:
    run:
      shell: bash

  steps: 
    - name: check out repository
      uses: actions/checkout@v3
      with:
        repository: precice/precice
        ref: ${{ inputs.precice-version }}
        path: precice
    
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake libeigen3-dev libxml2-dev libboost-all-dev petsc-dev python3-dev python3-numpy

    - name: Generate build directory
      working-directory: precice
      run: mkdir -p build

    - name: Configure
      working-directory: precice/build
      run: |
        cmake --version
        cmake -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/precice -DCMAKE_BUILD_TYPE=Release -DPRECICE_PETScMapping=OFF -DPRECICE_Python_Actions=OFF -DBUILD_TESTING=${{ inputs.build-tests }} ..

    - name: Compile
      working-directory: precice/build
      run: |
        make -j $(nproc)

    - name: Install
      working-directory: precice/build
      run: make install

    - name: Add to path
      run: |
        echo "PATH=$GITHUB_WORKSPACE/precice/bin:$PATH" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$GITHUB_WORKSPACE/precice/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=$GITHUB_WORKSPACE/precice/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
        echo "CPATH=$GITHUB_WORKSPACE/precice/include:$CPATH" >> $GITHUB_ENV
        echo "CMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/precice:$CMAKE_PREFIX_PATH" >> $GITHUB_ENV