name: 'Build preCICE'
description: 'Installs preCICE in the given prefix and adds it to the path.'

inputs:
  precice-version:
    required: true
    default: 'develop'
    description: 'The version of preCICE to use. Can be a branch or tag or SHA. Defaults to `develop`'
  build-tests:
    required: false
    default: 'OFF'
    description: 'Whether to build tests. Default is `OFF`'
  install-prefix:
    required: false
    default: '$HOME/precice'
    description: 'The installation prefix for preCICE. Default is `$HOME/precice`'

runs:
  using: "composite"
  steps: 

    - name: check for release # if the version is a release, install from prebuilt binaries
      id: check
      shell: bash
      run: |
        if [[ ${{ inputs.precice-version }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "::set-output name=release::true"
        else
          echo "::set-output name=release::false"
        fi

    - name: install prebuilt binaries
      if: steps.check.outputs.release == 'true'
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y wget
        wget https://github.com/precice/precice/releases/download/${{ inputs.precice-version }}/libprecice2_${{ inputs.precice-version\#"v" }}_$(lsb_release -cs).deb
        sudo apt install -y ./libprecice2_${{ inputs.precice-version\#"v" }}_$(lsb_release -cs).deb
        rm libprecice2_${{ inputs.precice-version\#"v" }}_$(lsb_release -cs).deb
        exit 0

    - name: check out repository
      uses: actions/checkout@v3
      with:
        repository: precice/precice
        ref: ${{ inputs.precice-version }}
        path: precice
      env: 
        GITHUB_WORKSPACE: $HOME
    
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake libeigen3-dev libxml2-dev libboost-all-dev petsc-dev python3-dev python3-numpy
      shell: bash

    - name: Generate build directory
      shell: bash
      working-directory: precice
      env: 
        GITHUB_WORKSPACE: $HOME
      run: mkdir -p build

    - name: Show preCICE state
      shell: bash
      working-directory: precice
      run: git log -n 1

    - name: Configure
      shell: bash
      working-directory: precice/build
      env:
        GITHUB_WORKSPACE: $HOME
      run: |
        cmake --version
        cmake -DCMAKE_INSTALL_PREFIX=${{ inputs.install-prefix }} -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=${{ inputs.build-tests }} ..

    - name: Compile
      shell: bash
      working-directory: precice/build
      env:
        GITHUB_WORKSPACE: $HOME
      run: |
        make -j $(nproc)

    - name: Install
      shell: bash
      working-directory: precice/build
      env:
        GITHUB_WORKSPACE: $HOME
      run: make install

    - name: Add to path
      shell: bash
      run: |
        echo "PATH=$HOME/precice/bin:$PATH" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$HOME/precice/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=$HOME/precice/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
        echo "CPATH=$HOME/precice/include:$CPATH" >> $GITHUB_ENV
        echo "CMAKE_PREFIX_PATH=$HOME/precice:$CMAKE_PREFIX_PATH" >> $GITHUB_ENV