name: 'Test setup-precice-action'
on: 
  push:
    - main
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        precice-version: ['develop', 'main']

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: debug
        run: |
          echo $GITHUB_WORKSPACE
          ls -la
          echo $PWD
      
      - name: Set up preCICE
        uses: ./
        with:
          precice-version: ${{ matrix.precice-version }}
          build-tests: 'ON'

      - name: debug
        run: |
          echo $GITHUB_WORKSPACE
          ls -la
          echo $PWD
          echo $LD_LIBRARY_PATH

      - name: Run tests
        working-directory: precice/build
        run: |
          ctest
          make test_install
