name: 'Test setup-precice-action'
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        precice-version: ['develop', 'master']

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up precice
        uses: ./
        with:
          precice-version: ${{ matrix.precice-version }}
