name: 'Test setup-precice-action'
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        precice-version: ['develop', 'main', 'v3.2.0']

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: debug
        run: |
          echo $GITHUB_WORKSPACE
          ls -la
          echo $PWD
      
      - name: Set up preCICE
        uses: ./
        with:
          precice-version: ${{ matrix.precice-version }}
          build-tests: 'ON'

      - name: Check release version
        id: check-release
        run: |
          if [[ ${{ matrix.precice-version }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "release=true" >> $GITHUB_OUTPUT
            echo "release=true"
          else
            echo "release=false" >> $GITHUB_OUTPUT
            echo "release=false"
          fi

      - name: debug
        run: |
          echo ${{ steps.check-release.outputs.release }}
          echo $GITHUB_WORKSPACE
          ls -la
          echo $PWD
          echo $LD_LIBRARY_PATH


      - name: Run tests if not release tag
        if: steps.check-release.outputs.release == 'false'
        working-directory: precice/build
        run: |
          ctest
          make test_install
